service: mattlau-backend
provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: ap-southeast-2
  memorySize: 128
functions:
  app:
    handler: src/app.handler
    environment: ${file(env.json)}
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
          response:
            contentHandling: CONVERT_TO_BINARY
plugins:
  - serverless-plugin-typescript
  - serverless-apigw-binary
custom:
  apigwBinary:
    types:
      - 'image/jpeg'
      - 'image/gif'
      - 'image/png'
      - 'video/mp4'
      - 'audio/mpeg'